services:
  nginx:
    image: nginx:alpine
    environment:
      - FRONTEND=host.docker.internal:3000
      - BACKEND=host.docker.interal:8000
      - NGINX_SERVER_NAME=localhost
    ports:
      - 8080:8080
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/templates/default.conf.template
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    container_name: flash_mongo
    image: "mongo:latest"
    ports:
      - 27017:27017
    volumes:
      - "./mongoDB:/data/db"
    restart: always

  mongo-express:
    image: "mongo-express:latest"
    ports:
      - 8001:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: duotone-dark
    restart: always

  backend:
    container_name: flash_backend
    build: ../backend
    environment:
      - MONGO_HOST=flash_mongo
      - APP_OPENAI=${APP_OPENAI}
    ports:
      - 8000:8000
    profiles:
      - app
      - frontend

  frontend:
    container_name: flash_frontend
    build: ../frontend
    ports:
      - 3000:3000
    profiles:
      - app
      - backend

volumes:
  mongoDB:
