/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Jobs
 */
export interface Jobs {
    /**
     * 
     * @type {string}
     * @memberof Jobs
     */
    'title': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Jobs
     */
    'locations': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Jobs
     */
    'description': string;
}

