/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Jobs } from './jobs';

/**
 * 
 * @export
 * @interface OfferingRequest
 */
export interface OfferingRequest {
    /**
     * 
     * @type {string}
     * @memberof OfferingRequest
     */
    'reasoning': string;
    /**
     * 
     * @type {Array<Jobs>}
     * @memberof OfferingRequest
     */
    'output': Array<Jobs>;
}

