/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Personality
 */
export interface Personality {
    /**
     * 
     * @type {number}
     * @memberof Personality
     */
    'openness'?: number;
    /**
     * 
     * @type {number}
     * @memberof Personality
     */
    'neuroticism'?: number;
    /**
     * 
     * @type {number}
     * @memberof Personality
     */
    'agreeableness'?: number;
    /**
     * 
     * @type {number}
     * @memberof Personality
     */
    'extraversion'?: number;
    /**
     * 
     * @type {number}
     * @memberof Personality
     */
    'conscientiousness'?: number;
}

