/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Personality } from './personality';
// May contain unused imports in some cases
// @ts-ignore
import type { Question } from './question';
// May contain unused imports in some cases
// @ts-ignore
import type { UserLevel } from './user-level';

/**
 * 
 * @export
 * @interface UserBase
 */
export interface UserBase {
    /**
     * 
     * @type {string}
     * @memberof UserBase
     */
    'name_first': string;
    /**
     * 
     * @type {string}
     * @memberof UserBase
     */
    'name_second': string;
    /**
     * 
     * @type {string}
     * @memberof UserBase
     */
    'file_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserBase
     */
    'openai_file_id'?: string | null;
    /**
     * 
     * @type {UserLevel}
     * @memberof UserBase
     */
    'level'?: UserLevel;
    /**
     * 
     * @type {Personality}
     * @memberof UserBase
     */
    'personality'?: Personality;
    /**
     * 
     * @type {Array<Question>}
     * @memberof UserBase
     */
    'questions'?: Array<Question>;
}



