/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Personality } from './personality';
// May contain unused imports in some cases
// @ts-ignore
import type { UserLevel } from './user-level';

/**
 * 
 * @export
 * @interface UserUpdate
 */
export interface UserUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserUpdate
     */
    'file_id'?: string | null;
    /**
     * 
     * @type {UserLevel}
     * @memberof UserUpdate
     */
    'level'?: UserLevel | null;
    /**
     * 
     * @type {Personality}
     * @memberof UserUpdate
     */
    'personality'?: Personality | null;
}



